### ISSUE TITLE
Error loading plugin on Mac

### ISSUE THREAD

**Issue by FlipMuc** [mfkrause/homebridge-people-pro#4]
received the following error when trying this pluging on my homebridge hosted on a Mac Mini w/ Bug Sur:

ERRORR LOADING PLUGIN homebridge-people-pro:
 ReferenceError: Characteristic is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-people-pro/base/characteristics/last_activation.js:1:44)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-people-pro/base/characteristics/index.js:1:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by mfkrause** [comment]
Hey! Thanks for the issue report.
Please try installing the patch for this by using the command `sudo npm install -g --unsafe-perm mfkrause/homebridge-people-pro#develop` and tell me if it works then. Please note that the develop branch you're installing from then is not stable and you should probably uninstall it again afterward if you're looking to use this on your main Homebridge. If the patch works I will migrate it to the master branch (and to the NPM registry) in about 4-5 hours. After that you can install the plug-in using the normal way again.

**Comment by mfkrause** [comment]
Tested on two different macOS machines and deemed as resolved with #5. Please update to v0.9.1.
